<?php
if(!defined('PART'))exit;
include('_c/function/bank.autoload.php');
include('_c/function/chat.autoload.php');
include('_c/function/class.autoload.php');
include('_c/function/login.autoload.php');
include('_c/function/power.autoload.php');
include('_c/function/refresh.autoload.php');
include('_c/function/vou.autoload.php');
?>