<?php
if(!defined('PART'))exit;
include('_m/function/bank.autoload.php');
include('_m/function/chat.autoload.php');
include('_m/function/class.autoload.php');
include('_m/function/login.autoload.php');
include('_m/function/power.autoload.php');
include('_m/function/refresh.autoload.php');
include('_m/function/vou.autoload.php');
?>