<?php
if(!defined('PART'))exit;
include_once(APP_PATH.'function/function.php');
include_once(APP_PATH.'function/'.DB_MYSQL.'.php');
include_once(APP_PATH.'function/js.php');
include_once(APP_PATH.'function/sms.php');
include_once(APP_PATH.'config/config.php');
include_once(APP_PATH.'function/utf8.php');
include_once(APP_PATH.'library/image.php');
?>